FROM yoanlin/opencv-python3:latest

MAINTAINER Yo-An Lin <yoanlin93@gmail.com>

RUN pip install cython \
 && pip install six \
 && pip install Pillow \
 && pip install tensorflow \
 && pip install dlib \
 && pip install face_recognition \
 && pip install pandas \
 && rm -rf ~/.cache/pip
